// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xyuyvtqmwjeklmxrmyed.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh5dXl2dHFtd2pla2xteHJteWVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NjkxNzMsImV4cCI6MjA3MzQ0NTE3M30.NIp_v-utatS5mVYX5KiGO7BIrfBv4nkNoP7k32agOl8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});